* Rants About Flawed Design

We live in a world filled with flawed design. The consequences of flawed design
is that the quality (and length) of every one of our lives is significantly
diminished.

All flawed design, including missing design, offers an opportunity for good
creative designers to correct or supply what's missing. Unfortunately, there is
usually
- great difficulty in getting partnership in these enterprises
- significant friction in the acceptance of these solutions
In other words, poor design and missing design is usually not an accident!

None of these obstacles should be used as an excuse to not move ahead. They just
mean that these opportunities must be approached with skill and resources. Skill
and resources which good creative designers might not have. This can be
frustrating!

The rants in this collection are an intended to release some of the frustration
of these challenges. The intention is that they will be followed up with
strategic action.

Alas, this doesn't seem to work:
#+begin_src ex
.,$g/^- .* Rant/!tr 'A-Z ' 'a-z-' | sed 's/^--\(.*-rant\)/[[[[file:\1.org][\1.org]][\1]]/'
#+end_src

So we bring out the big gun:
#+begin_src awk
.,$!awk '!/^- [^[].* Rant/{print}/^- [^[].* Rant/{sub(/^- /, "");printf("- [[file:\%s.org][\%s]]\n", tolower(gensub(/ /,"-","g",$0)), $0);}'
#+end_src

Computer Languages
- [[file:files-vs-database-rant.org][Files vs Database Rant]]
- [[file:database-rant.org][Database Rant]]
- [[file:monotonicity-rant.org][Monotonicity Rant]]
- [[file:lisp-rant.org][Lisp Rant]]
- [[file:scheme-rant.org][Scheme Rant]]
- [[file:racket-rant.org][Racket Rant]]
- Spreadsheet Rant
- Word Processor Rant
- Shell Rant
